### PR TITLE
Convert the code to python 3.0

### PR DESCRIPTION
**Pull request by JeffTheK**
I have converted all the files to python 3.0 + fixed some issues.
There were some deprecated/not supported libraries, I fixed them.
I've tested the `aristo.py` on my Linux machine and it seems to work fine.
I haven't tested any options but the main code works fine.
It should also work on your machine.

I am planning to add script that automatically installs all the needed modules.
The colors implementation is quite messy, but we can improve it by having one file with all colors or use some kind of module.

Also, for some reason it requires sudo to work, it shouldn't that's why I comented out the requirement for now, if this breaks some code, I will rewrite it so it can be run with usual permissions.

Feel free to ask me about changes!

### CODE REVIEW

**Comment by JeffTheK** [comment]
Also it searches for `agree.txt` file in the wrong directory. I don't know whether we should move the file or fix the code

**Comment by JeffTheK** [comment]
In the last commit I moved colors into one file so we don't have to repeat code

**Comment by AristodamusAdairs** [comment]
- [ ]

**Comment by AristodamusAdairs** [comment]
TYSM Jeff, Shwaika

**Pull request merged**
